# Generated by Django 5.1.7 on 2025-04-01 17:08

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLoginRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('code', models.CharField(default='59912', max_length=6, verbose_name='Code')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
            ],
            options={
                'verbose_name': 'SMS login request',
                'verbose_name_plural': 'SMS login requests',
            },
        ),
    ]
