# Generated by Django 5.1.7 on 2025-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsloginrequest',
            name='code',
            field=models.CharField(default='92556', max_length=6, verbose_name='Code'),
        ),
    ]
