# Generated by Django 5.1.7 on 2025-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_smsloginrequest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsloginrequest',
            name='code',
            field=models.CharField(default='05510', max_length=6, verbose_name='Code'),
        ),
    ]
