# Generated by Django 5.1.7 on 2025-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_alter_smsloginrequest_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsloginrequest',
            name='code',
            field=models.CharField(default='16576', max_length=6, verbose_name='Code'),
        ),
    ]
