# Generated by Django 5.1.7 on 2025-04-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0022_alter_smsloginrequest_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsloginrequest",
            name="code",
            field=models.CharField(default="60270", max_length=6, verbose_name="Code"),
        ),
    ]
