# Generated by Django 5.1.7 on 2025-04-21 22:08

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import gs_tools_django.core.validators.file_size
import gs_tools_django.files.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=gs_tools_django.files.models.uploaded_file_name,
                        validators=[
                            gs_tools_django.core.validators.file_size.FileSizeValidator(max_size=1),
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "zip",
                                    "rar",
                                    "mp3",
                                    "ogg",
                                    "wav",
                                    "mp4",
                                    "bmp",
                                    "jpeg",
                                    "jpg",
                                    "mpo",
                                    "png",
                                    "tif",
                                    "tiff",
                                    "webp",
                                ]
                            ),
                        ],
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(blank=True, null=True, verbose_name="MimeType"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.file",
                        verbose_name="File",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="file",
            name="users",
            field=models.ManyToManyField(
                related_name="files",
                through="files.UserFile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
    ]
