from celery.schedules import crontab

from .localization import TIME_ZONE
from .shared import env

CELERY_BROKER_URL = env("GSTOOLS_CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env("GSTOOLS_CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = env("GSTOOLS_CELERY_TIMEZONE", default=TIME_ZONE)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = env(
    "GSTOOLS_CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP",
    default=False,
)